const KEY='wanna-preview-v021';
const cards=[
{id:'shiki',emoji:'🍣',score:94,title:'Try Shiki',subtitle:'Japanese · Vienna · €€€',reason:'You and Benny both rate Japanese food highly.',interested:['Benny']},
{id:'bowling',emoji:'🎳',score:88,title:'Bowling night',subtitle:'Activity · 2–4 people',reason:'Benny and Moka are interested too.',interested:['Benny','Moka']},
{id:'schneeberg',emoji:'🏔️',score:84,title:'Schneeberg day trip',subtitle:'Outdoor · full day',reason:'Saved before and fits your weekend preferences.',interested:['Moka']},
{id:'cocktails',emoji:'🍸',score:82,title:'Cocktails somewhere new',subtitle:'Drinks · Vienna',reason:'A low-effort plan that fits your recent evenings.',interested:['Benny']}
];
const seedPlans=[
{id:'sushi',title:'Sushi night',emoji:'🍣',status:'PLANNING',people:['Andreas','Benny'],when:'Friday · 19:30',place:'KitchA',vote:null},
{id:'prague',title:'Prague weekend',emoji:'✈️',status:'READY_TO_CONFIRM',people:['Andreas','Benny','Moka'],when:'23–25 October',place:'Prague',vote:'YES'},
{id:'prater',title:'Prater after work',emoji:'🎡',status:'CONFIRMED',people:['Andreas','Moka'],when:'Tomorrow · 18:30',place:'Prater',vote:'YES'}
];
let state=load();let discoverIndex=state.discoverIndex||0;let pendingDiscover=null;let selectedPeople=new Set();
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{user:null,plans:seedPlans,decisions:{},discoverIndex:0,installDismissed:false}}catch(e){return{user:null,plans:seedPlans,decisions:{},discoverIndex:0,installDismissed:false}}}
function save(){state.discoverIndex=discoverIndex;localStorage.setItem(KEY,JSON.stringify(state))}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function pickUser(name){state.user=name;save();document.getElementById('chooser').classList.add('hidden');renderAll();toast('Hi '+name+' 👋')}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.target===id));if(id==='create')renderCreate();if(id==='plans')renderPlans();window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>show(b.dataset.target));
function fmtDate(){return new Intl.DateTimeFormat('en',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}
function planCard(p,action=true){const statusClass=p.status==='READY_TO_CONFIRM'?'ready':p.status==='CONFIRMED'?'confirmed':'';return `<div class="card compact" onclick="openPlan('${p.id}')"><div class="planline"><div class="planemoji">${p.emoji}</div><div class="plantext"><div class="status ${statusClass}">${p.status.replaceAll('_',' ')}</div><h2>${esc(p.title)}</h2><div class="muted mini">${esc(p.people.join(' · '))}${p.when?' · '+esc(p.when):''}</div></div>${action?'<div>›</div>':''}</div></div>`}
function renderHome(){const needs=state.plans.filter(p=>p.status==='PLANNING'||p.status==='READY_TO_CONFIRM');const upcoming=state.plans.filter(p=>p.status==='CONFIRMED');document.getElementById('home').innerHTML=`<div class="top"><div class="date">${fmtDate()}</div><div class="pill">Local demo</div></div><h1>Good morning,<br>${esc(state.user||'friend')}</h1><div class="card"><div class="eyebrow">Quick start</div><h2>What do you wanna do?</h2><p class="muted">Start with an idea, a person, a date or a place.</p><button class="btn" onclick="event.stopPropagation();show('create')">＋ Create something</button></div><div class="heading"><h2>Needs you</h2><span>${needs.length}</span></div>${needs.length?needs.map(p=>planCard(p)).join(''):'<div class="card empty">Nothing waiting on you. Nice.</div>'}<div class="heading"><h2>For you</h2></div><div class="card"><div class="eyebrow">✨ Good window</div><h2>Make something happen</h2><p class="muted">Turn a loose idea into a plan in a few taps.</p><button class="btn soft" onclick="show('create')">Make a plan</button></div>${upcoming.length?'<div class="heading"><h2>Upcoming</h2></div>'+upcoming.map(p=>planCard(p)).join(''):''}`}
function renderDiscover(){const c=cards[discoverIndex%cards.length];const match=state.lastMatch?cards.find(x=>x.id===state.lastMatch):null;document.getElementById('discover').innerHTML=`<div class="top"><div><div class="eyebrow">Private until mutual</div><h1 style="margin-bottom:5px">Discover</h1></div><div>⚙</div></div><p class="muted">Things you might actually wanna do.</p>${match?`<div class="card match"><div class="eyebrow">It's a match ✨</div><h2>${match.emoji} ${esc(match.title)}</h2><p class="muted">${esc(match.interested.join(' & '))} ${match.interested.length===1?'wants':'want'} this too.</p><button class="btn soft" onclick="startFromDiscover('${match.id}')">Create Plan</button></div>`:''}<div class="card hero"><div class="emoji">${c.emoji}</div><div class="score">${c.score}% FOR YOU</div><h1 style="margin:4px 0">${esc(c.title)}</h1><div>${esc(c.subtitle)}</div><p class="muted">${esc(c.reason)}</p></div><div class="actions"><button class="btn ghost" onclick="decide('PASS')">Pass</button><button class="btn soft" onclick="decide('SAVE')">Save</button><button class="btn" onclick="decide('WANNA')">Wanna</button></div>`}
function decide(d){const c=cards[discoverIndex%cards.length];state.decisions[c.id]=d;if(d==='WANNA'&&c.interested.length){state.lastMatch=c.id;toast("It's a match ✨")}else if(d==='SAVE')toast('Saved for later');else if(d==='PASS')toast('Passed');discoverIndex=(discoverIndex+1)%cards.length;save();renderDiscover()}
function startFromDiscover(id){pendingDiscover=cards.find(c=>c.id===id)||null;selectedPeople=new Set(pendingDiscover?.interested||[]);show('create')}
function renderCreate(){const p=pendingDiscover;const people=['Andreas','Benny','Moka'].filter(x=>x!==state.user);document.getElementById('create').innerHTML=`<div class="eyebrow">New plan</div><h1>Create</h1><p class="muted">Start anywhere. Wanna asks only for what is missing.</p><div class="card"><label class="eyebrow">What are you thinking?</label><textarea id="planTitle" class="input" placeholder="Sushi Friday…">${p?esc(p.title):''}</textarea><div style="height:13px"></div><label class="eyebrow">With who?</label><div class="people-grid" style="margin-top:9px">${people.map(name=>`<button id="person-${name}" class="person ${selectedPeople.has(name)?'active':''}" onclick="togglePerson('${name}')"><div class="avatar">${name[0]}</div>${name}</button>`).join('')}</div><div style="height:15px"></div><label class="eyebrow">When?</label><div class="row" style="margin-top:9px"><button class="chip" data-when="Tonight" onclick="selectWhen(this)">Tonight</button><button class="chip" data-when="Tomorrow" onclick="selectWhen(this)">Tomorrow</button><button class="chip" data-when="This weekend" onclick="selectWhen(this)">This weekend</button><button class="chip active" data-when="Decide later" onclick="selectWhen(this)">Decide later</button></div><div style="height:15px"></div><button class="btn block" onclick="createPlan()">Create plan</button></div><div class="card"><h2>Or start with…</h2><p class="muted">People, date, place or a link.</p><div class="row"><span class="chip">👥 People</span><span class="chip">🗓 Date</span><span class="chip">📍 Place</span><span class="chip">🔗 Link</span></div></div>`;window.selectedWhen='Decide later'}
function togglePerson(name){selectedPeople.has(name)?selectedPeople.delete(name):selectedPeople.add(name);document.getElementById('person-'+name)?.classList.toggle('active',selectedPeople.has(name))}
function selectWhen(el){document.querySelectorAll('[data-when]').forEach(x=>x.classList.remove('active'));el.classList.add('active');window.selectedWhen=el.dataset.when}
function createPlan(){const title=document.getElementById('planTitle').value.trim();if(!title){toast('Give the plan a name');return}const when=window.selectedWhen||'Decide later';const plan={id:'plan-'+Date.now(),title,emoji:pendingDiscover?.emoji||'✨',status:when==='Decide later'?'IDEA':'PLANNING',people:[state.user,...selectedPeople].filter(Boolean),when:when==='Decide later'?'':when,place:pendingDiscover?.subtitle?.split(' · ')[1]||'',vote:null};state.plans.unshift(plan);pendingDiscover=null;selectedPeople=new Set();save();renderAll();openPlan(plan.id);toast('Plan created')}
function renderPlans(){const groups=['IDEA','PLANNING','READY_TO_CONFIRM','CONFIRMED'];document.getElementById('plans').innerHTML=`<div class="eyebrow">Everything in motion</div><h1>Plans</h1>${groups.map(g=>{const list=state.plans.filter(p=>p.status===g);if(!list.length)return'';return `<div class="heading"><h2>${g==='IDEA'?'Ideas':g==='PLANNING'?'Planning':g==='READY_TO_CONFIRM'?'Ready to confirm':'Confirmed'}</h2><span>${list.length}</span></div>${list.map(p=>planCard(p)).join('')}`}).join('')}`}
function renderYou(){document.getElementById('you').innerHTML=`<div class="profile"><div><div class="eyebrow">Your profile</div><h1 style="margin-bottom:3px">${esc(state.user||'You')}</h1><div class="muted">@${esc((state.user||'you').toLowerCase())}</div></div><div class="profile-avatar">${esc((state.user||'Y')[0])}</div></div><div class="card"><div class="eyebrow">Your preview</div><div class="stats"><div class="stat"><b>${state.plans.length}</b><span>plans</span></div><div class="stat"><b>${Object.values(state.decisions).filter(v=>v==='WANNA').length}</b><span>wannas</span></div><div class="stat"><b>${Object.values(state.decisions).filter(v=>v==='SAVE').length}</b><span>saved</span></div></div></div><div class="heading"><h2>Memories</h2></div><div class="photoGrid"><div class="photo">🍣</div><div class="photo">✈️</div><div class="photo">🎡</div><div class="photo">🍸</div><div class="photo">🏔️</div><div class="photo">🎬</div></div><div class="card"><div class="eyebrow">Preview note</div><h2>Data stays on this device</h2><p class="muted">The shared Supabase backend comes next. For now this is perfect for testing the flow and interface.</p><button class="btn ghost" onclick="resetDemo()">Reset this demo</button></div>`}
function openPlan(id){const p=state.plans.find(x=>x.id===id);if(!p)return;const ready=p.status==='READY_TO_CONFIRM';const confirmed=p.status==='CONFIRMED';document.getElementById('sheetContent').innerHTML=`<div class="eyebrow">${p.status.replaceAll('_',' ')}</div><h1>${p.emoji} ${esc(p.title)}</h1><div class="card"><div class="eyebrow">People</div><h2>${esc(p.people.join(' · '))}</h2>${p.when?`<p class="muted">🗓 ${esc(p.when)}</p>`:''}${p.place?`<p class="muted">📍 ${esc(p.place)}</p>`:''}</div>${!confirmed?`<div class="card"><div class="eyebrow">Your vote</div><h2>Does this work?</h2><div class="actions"><button class="btn ${p.vote==='NO'?'':'ghost'}" onclick="votePlan('${p.id}','NO')">No</button><button class="btn ${p.vote==='MAYBE'?'':'soft'}" onclick="votePlan('${p.id}','MAYBE')">Maybe</button><button class="btn" onclick="votePlan('${p.id}','YES')">Yes</button></div></div>`:''}<button class="btn block ${confirmed?'ghost':''}" onclick="advancePlan('${p.id}')">${confirmed?'Confirmed ✓':ready?'Confirm plan':'Ready to confirm'}</button><div style="height:9px"></div><button class="btn ghost block" onclick="closeSheet()">Close</button>`;document.getElementById('overlay').classList.add('show')}
function votePlan(id,v){const p=state.plans.find(x=>x.id===id);if(!p)return;p.vote=v;save();openPlan(id);renderAll();toast('Vote saved: '+v)}
function advancePlan(id){const p=state.plans.find(x=>x.id===id);if(!p)return;if(p.status==='CONFIRMED'){closeSheet();return}p.status=p.status==='READY_TO_CONFIRM'?'CONFIRMED':'READY_TO_CONFIRM';save();openPlan(id);renderAll();toast(p.status==='CONFIRMED'?'Plan confirmed 🎉':'Ready to confirm')}
function closeSheet(){document.getElementById('overlay').classList.remove('show')}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1900)}
function dismissInstall(){state.installDismissed=true;save();document.getElementById('installTip').classList.add('hidden')}
function resetDemo(){localStorage.removeItem(KEY);location.reload()}
function renderAll(){renderHome();renderDiscover();renderCreate();renderPlans();renderYou();document.getElementById('installTip').classList.toggle('hidden',!!state.installDismissed)}
if(state.user)document.getElementById('chooser').classList.add('hidden');renderAll();